default:
  image: docker:28.3.2
  services:
    - docker:28.3.2-dind

# This builds all necessary container for the whole setup
before_script:
  - docker compose up -d

stages:
  - all_in_one

all_in_one:
  stage: all_in_one
  script:
    - docker compose --profile ci up -d
    # Run all tests and generates coverage
    - docker exec ci-test sh -c "cargo tarpaulin --ignore-tests --engine Llvm --out xml"
  # Code coverage related settings
  coverage: '/^\d+.\d+% coverage/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

after_script:
  - docker compose down --volumes --remove-orphans
