# This docker compose file is intended to be used for development 
# Simply running 
#   docker compose up -d 
# should bring up all relevant services
#
# NOTE: The Dockerfile uses your local rust installation!

services:  # Define the services to run
  sb-postgres:  # PostgreSQL service
    image: postgres:17-alpine  # Use the PostgreSQL image from Docker Hub
    container_name: postgres  # Assign a name to the container
    restart: always
    profiles:
      - runtime
    environment:  # Set environment variables for PostgreSQL
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:  # Create a volume to store PostgreSQL data
      - postgres:/var/lib/postgresql/data
      # Start script for creating the database.
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
      # OPTIONAL Example data
      - ./example:/example/
    networks:
      - "sb-net"
    healthcheck:  # Define a health check for the container
      test: ["CMD", "pg_isready", "-h", "postgres", "-U", "${PSQL_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  sb-pgadmin:  # pgAdmin service
    image: dpage/pgadmin4  # Use the pgAdmin image from Docker Hub
    profiles:
      - runtime
    container_name: pgadmin  # Assign a name to the container
    ports:
      - "8084:80"
    environment:  # Set environment variables for pgAdmin
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    volumes:  # Create a volume to store pgAdmin data
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - "sb-net"
    restart: always  # Restart the container if it stops
    depends_on:  # Specify that this service depends on the PostgreSQL service
      - sb-postgres

  sb-build-db:
    image: postgres:17-alpine
    profiles:
      - precompile
    network_mode: host
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: builddb
  
  sb-sensbee:
    container_name: sensbee
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      # NOTE this is just used during build for sqlx migration testing
      args:
        - DATABASE_URL=postgres://user:pw@localhost:5432/builddb
    profiles:
      - runtime
    depends_on:
      - sb-postgres
    networks:
      - "sb-net"
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
  
  sb-SBMI-nginx:
    image: nginx:alpine
    profiles:
      - runtime
    container_name: sbmi
    ports:
      - "8082:80"
    volumes:
      - ./sbmi/static/:/usr/share/nginx/html/:ro
      - ./sbmi/nginx/nginx-no-cache.conf:/etc/nginx/nginx.conf:ro
    networks:
      - "sb-net"

volumes:  # Define named volumes for data storage
  postgres:
  pgadmin-data:

networks:
  sb-net:
    driver: bridge